---
- name: Install WMI Exporter
  hosts: servers
  vars:
    wmi_exporter_download_folder: c:\WMI-Exporter
    wmi_exporter_installer_url: https://github.com/prometheus-community/windows_exporter/releases/download/v0.16.0/
    wmi_exporter_installer_filename: windows_exporter-0.16.0-amd64.msi
  tasks:
    - name: Create WMI-Exporter Folder
      win_file:
        path: "{{ wmi_exporter_download_folder }}"
        state: directory

    - name: "Download {{ wmi_exporter_installer_url }}\\{{ wmi_exporter_installer_filename }} to specified path"
      win_get_url:
        url:  "{{ wmi_exporter_installer_url }}\\{{ wmi_exporter_installer_filename }}"
        dest: "C:\\WMI-Exporter\\{{ wmi_exporter_installer_filename }}"
        proxy_username: "{{ ansible_user }}"
        proxy_password: "{{ ansible_password }}"

    - name: Install the WMI Exporter
      win_package:
        path: "C:\\WMI-Exporter\\{{ wmi_exporter_installer_filename }}"
        state: present
        wait_for_children: true
